iya~~

diff --git a/.github/workflows/dump_helmfile_template.yaml b/.github/workflows/dump_helmfile_template.yaml
--- a/.github/workflows/dump_helmfile_template.yaml
+++ b/.github/workflows/dump_helmfile_template.yaml
@@ -10,7 +10,7 @@ on:
   workflow_dispatch:
 
 jobs:
-  generate-helmfile-template:
+  dump-helmfile-template:
     runs-on: ubuntu-latest
 
     steps:
@@ -51,3 +51,20 @@ jobs:
         run: |
           git switch -c temp-dump
           git push origin temp-dump
+
+  cleanup:
+    needs: dump-helmfile-template
+    runs-on: ubuntu-latest
+    if: failure()
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
+
+      - name: Cleanup temp-dump branch
+        run: |
+          git config --global user.name 'GitHub Actions'
+          git config --global user.email 'github-actions@users.noreply.github.com'
+          git fetch origin temp-dump:temp-dump || echo "temp-dump branch not found"
+          git push origin --delete temp-dump || echo "temp-dump branch not found"
diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -6,9 +6,7 @@ on:
       - main
     paths:
       - manifests/**
-    paths-ignore:
-      - manifests/helmfiles/**
-      - app/**
+      - !manifests/helmfiles/**
   workflow_run:
     workflows: ["Build-and-Push", "Dump-Helmfile-Template"]
     types:
@@ -35,14 +33,11 @@ jobs:
           git switch release
           if git rev-parse --verify temp-build; then
             git merge --no-ff --allow-unrelated-histories temp-build -m "Merge build changes"
+            git push origin --delete temp-build || echo "temp-build branch not found"
           fi
           if git rev-parse --verify temp-dump; then
             git merge --no-ff --allow-unrelated-histories temp-dump -m "Merge dump changes"
+            git push origin --delete temp-dump || echo "temp-dump branch not found"
           fi
           git merge main --no-ff -m "Release changes"
           git push origin release
-
-      - name: Cleanup temporary branches
-        run: |
-          git push origin --delete temp-build || echo "temp-build branch not found"
-          git push origin --delete temp-dump || echo "temp-dump branch not found"
